In [3]:
import numpy as np

Question 1:

In [8]:
# a.
arr1 = np.array([1,2,3,6,4,5])
rev = np.flip(arr1)
print("reversed array:",rev)

# b.
arr2 = np.array([[1,2,3],[2,4,5],[1,2,3]])
fl = arr2.flatten()
rv = arr2.ravel()
print("Flatten array using method 1:",fl)
print("Flatten array using method 2:",rv)

# c.
arr3 = np.array([[1,2],[3,4]])
arr4 = np.array([[1,2],[3,4]])
print("Are both arrays equal?",np.array_equal(arr3,arr4))

# d.
## i)
arr5 = np.array([1,2,3,4,5,1,2,1,1,1])
u, c = np.unique(arr5, return_counts=True)
freq = u[np.argmax(c)]
i = np.where(arr5==freq)[0]
print("Most frequent:", freq, "Indices:", i)

## ii)
arr6 = np.array([1,1,1,2,3,4,2,4,3,3])
u, c = np.unique(arr5, return_counts=True)
freq = u[np.argmax(c)]
i = np.where(arr6==freq)[0]
print("Most frequent:", freq, "Indices:", i)

# e.
m = np.matrix('[4,1,9;12,3,1;4,5,6]')
print("Sum:", m.sum())
print("Row-wise um:", m.sum(axis=1))
print("Column-wise sum:", m.sum(axis=0))

# f.
arr = np.array([[55,25,15],[30,44,2],[11,45,77]])
## i)
print("Sum of diagonals:", np.trace(arr))

## ii)
ev, evec = np.linalg.eig(arr)
print("Eigen Values:",ev)

## iii)
print("Eigen Vectors:",evec)

## iv)
inv = np.linalg.inv(arr)
print("Inverse:",inv)

## iv)
d = np.linalg.det(arr)
print("Determinant:",d)

# g.
## i)
p1 = np.array([[1,2],[2,3]])
q1 = np.array([[4,5],[6,7]])
prod = np.dot(p1,q1)
print("Multiplication:", prod)
print("Covariance:",np.cov(p1.T,q1.T))

## ii)
p2 = np.array([[1,2],[2,3],[4,5]])
q2 = np.array([[4,5,1],[6,7,2]])
prod = np.dot(p2,q2)
p = p2.flatten()
q = q2.flatten()
print("Multiplication:", prod)
print("Covariance:",np.cov(p.T,q.T))

# h.
x = np.array([[2,3,4],[3,2,9]])
y = np.array([[1,5,0],[5,10,3]])
inn = np.inner(x,y)
out = np.outer(x,y)
print("Inner:",inn)
print("Outer:",out)

from itertools import product
c = np.array(list(product(x.flatten(), y.flatten())))
print("Cartesian:",c)

reversed array: [5 4 6 3 2 1]
Flatten array using method 1: [1 2 3 2 4 5 1 2 3]
Flatten array using method 2: [1 2 3 2 4 5 1 2 3]
Are both arrays equal? True
Most frequent: 1 Indices: [0 5 7 8 9]
Most frequent: 1 Indices: [0 1 2]
Sum: 45
Row-wise um: [[14]
 [16]
 [15]]
Column-wise sum: [[20  9 16]]
Sum of diagonals: 176
Eigen Values: [98.16835147 28.097044   49.73460452]
Eigen Vectors: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001
Multiplication: [[16 19]
 [26 31]]
Covariance: [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]
Multiplication: [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance: [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]
Inner: [[17 52]
 [13 62]]
Outer: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]

Question 2:

In [11]:
# a.
a = np.array([[1,-2,3],[-4,5,-6]])

## i)
ab = np.abs(a)
print("Absolute:", ab)

## ii)
print("Flattened Percentiles:", np.percentile(a.flatten(),[25, 50, 75]))
print("Column Percentiles:", np.percentile(a, [25, 50, 75], axis=0))
print("Row Percentiles:", np.percentile(a, [25, 50, 75], axis=1))

## iii)
print("Mean:", [np.mean(a.flatten()), np.mean(a, axis=0), np.mean(a, axis=1)])
print("Median:", [np.median(a.flatten()), np.median(a, axis=0), np.median(a, axis=1)])
print("Std Dev:", [np.std(a.flatten()), np.std(a, axis=0), np.std(a, axis=1)])

# b.
b = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print("Floor:", np.floor(b))
print("Ceil:", np.ceil(b))
print("Trunc:", np.trunc(b))
print("Round:", np.round(b))

Absolute: [[1 2 3]
 [4 5 6]]
Flattened Percentiles: [-3.5 -0.5  2.5]
Column Percentiles: [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Row Percentiles: [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean: [-0.5, array([-1.5,  1.5, -1.5]), array([ 0.66666667, -1.66666667])]
Median: [-0.5, array([-1.5,  1.5, -1.5]), array([ 1., -4.])]
Std Dev: [3.8622100754188224, array([2.5, 3.5, 4.5]), array([2.05480467, 4.78423336])]
Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Round: [-2. -2. -0.  0.  2.  2.  3.]


Question 3:

In [12]:
# a.
ar = np.array([10, 52, 62, 16, 16, 54, 453])
## i)
print("Sorted:", np.sort(ar))

## ii)
print("Sorted Indices:", np.argsort(ar))

## iii)
print("4 Smallest:", np.sort(ar)[:4])

## iv)
print("5 Largest:", np.sort(ar)[-5:])

# b.
arrr = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
## i)
print("Integers only:", arrr[arrr == arrr.astype(int)])

## ii)
print("Floats only:", arrr[arrr != arrr.astype(int)])

Sorted: [ 10  16  16  52  54  62 453]
Sorted Indices: [0 3 4 1 5 2 6]
4 Smallest: [10 16 16 52]
5 Largest: [ 16  52  54  62 453]
Integers only: [1. 2. 3. 2.]
Floats only: [1.2 2.2]


Question 4:

In [ ]:
# a.
from PIL import Image

def img_to_array(path):
    img = Image.open(path)
    img_array = np.array(img)
    if img.mode == 'RGB':
        np.savetxt("rgb_image.txt", img_array.reshape(-1, 3), fmt='%d')
    elif img.mode == 'L':
        np.savetxt("gray_image.txt", img_array, fmt='%d')
    else:
        raise ValueError("Unsupported image mode")
    print("Saved successfully!")
     
# b.
gray_loaded = np.loadtxt("gray_image.txt", dtype=int)
rgb_loaded = np.loadtxt("rgb_image.txt", dtype=int).reshape(-1, 3)